DROP TABLE [dbo].[Perguntas];
GO
CREATE TABLE [dbo].[Perguntas] (
    [IdPergunta] int IDENTITY(1,1) NOT NULL,
    [enunciado] nvarchar(max)  NOT NULL,
    [dificuldade] int  NOT NULL,
    [alternativaCorreta] nvarchar(max)  NOT NULL,
    [alternativaIncorreta1] nvarchar(max)  NOT NULL,
    [alternativaIncorreta2] nvarchar(max)  NOT NULL,
    [alternativaIncorreta3] nvarchar(max)  NOT NULL,
    [alternativaIncorreta4] nvarchar(max)  NOT NULL,
    [vezesRespondidaAltCorreta] int  NOT NULL,
    [vezesRespondidaAltIncorreta1] int  NOT NULL,
    [vezesRespondidaAltIncorreta2] int  NOT NULL,
    [vezesRespondidaAltIncorreta3] int  NOT NULL,
    [vezesRespondidaAltIncorreta4] int  NOT NULL,
    [Tema_IdTema] int  NOT NULL
);
GO
-- Creating primary key on [IdPergunta] in table 'Perguntas'
ALTER TABLE [dbo].[Perguntas]
ADD CONSTRAINT [PK_Perguntas]
    PRIMARY KEY CLUSTERED ([IdPergunta] ASC);
GO


-- Creating non-clustered index for FOREIGN KEY 'FK_PerguntaTema'
CREATE INDEX [IX_FK_PerguntaTema]
ON [dbo].[Perguntas]
    ([Tema_IdTema]);
GO

USE [Show de Perguntas]
GO
INSERT INTO dbo.Temas (descricao)
		VALUES ('Cinema')
INSERT INTO dbo.Temas (descricao)
		VALUES ('História')
GO
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Quais destes filmes Steven Spielberg não foi diretor','Transformers','E.T. - O Extraterrestre','Minority Report - A nova lei','Tubarão','O resgate do soldado Ryan',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Há várias premiações no meio cinematográfico. Quais destes não é uma premiação cinematográfica?','Filme de Ouro','Leão de Ouro','Framboesa de Ouro','Globo de Ouro','Urso de Ouro',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('O que Charles Chaplin interpretava em Tempos Modernos?','Operário','Vagabundo','Garçom','Ele mesmo','Ajudante',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual destes filmes brasileiros foi indicado a premiação do Oscar?','Cidade de Deus','Se eu Fosse Você','Lula, o Filho do Brasil','2 filhos de Francisco','Lua de Cristal',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Que personagem do Star Wars aparece em todos os episódios da trilogia?','Mestre Yoda','Darth Vader','Princesa Leia','Chewbacca','Obi-Wan Kenobi',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual dos filmes não foi produzido pela Walt Disney?','Madagascar','Procurando Nemo','As Crónicas de Nárnia: O Leão, a Feiticeira e o Guarda-roupa','WALL-E','Piratas do Caríbe: A maldição do Pérola Negra',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual dos filmes abaixo não foi produzido pela Warner Bros?','Piratas do Caríbe: A maldição do Pérola Negra','Pokémon, o Filme: Mewtwo Contra-Ataca','Matrix','Batman Begins','Harry Potter e a Ordem da Fênix',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Em qual dos filmes há uma temática fundamentada na primeira guerra mundial?','O último batalhão','O último dos moicanos','Círculo de Fogo','...E o vento levou','O resgate do soldado Ryan',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual país estrangeiro recebeu mais premiações do Oscar?','Itália','Brasil','França','Japão','Argentina',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Quem nunca fez um papel de ator de cinema?','George Lucas','Wood Allen','Charles Chaplin','Quentim Tarantino','Clint Eastwood',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual longa ganhou a estatueta de melhor filme do Oscar 2002?','Uma mente brilhante','O senhor dos Anéis: A sociedade do anel','Entre Quatro Paredes','Moulin Rouge - Amor em Vermelho','Assasinato em Gosford Park',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual foi o filme que ganhou o Oscar de melhor filme em 2001?','Gladiador','O tigre e o dragão','Menina de ouro','Titanic','A espera de um milagre',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Quem ganhou a estatueta de melhor filme em 2010?','Guerra ao terror','Avatar','Bastardos Inglórios','Up – Altas Aventuras','Amor sem escalas',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual dos filmes abaixo recebeu mais indicações ao Oscar?','Titanic','Forrest Gump','Gladiador','O Poderoso Chefão','Senhor dos Anéis: O retorno do rei',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Quem já foi ator e diretor do cinema brasileiro?','Amácio Mazzaropi','Fernando Meirelles','Sandra Werneck','Fernanda Montenegro','n.d.a.',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Nome do navegador português a quem é atribuído o descobrimento do Brasil','Pedro Álvares Cabral','Américo Vespúcio','Vasco da Gama','Cristóvão Colombo','Dom João VI',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Em que governo foi implantado o Real no Brasil?','Itamar Franco','FHC','Lula','Fernando Collor','José Sarney',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('No Brasil, quando comemoramos o Dia da Bandeira?','19 de novembro','15 de dezembro','7 de setembro','22 de abril','19 de maio',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Complete: A nacionalidade da Joana D´Arc era _______.','Francesa',' Italiana','Inglesa','Flandesa','Turca',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Quando começou a Segunda Guerra Mundial?','1  de setembro de 1939','5 de fevereiro de 1920','26 de outubro de 1932','19 de maio de 1930','31 de dezembro de 1929',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Durante a Idade Média, os cristãos do Ocidente organizaram expedições contra os “infiéis” que ocupavam os Lugares Santos. Quem eram esses “infiéis” ?','Mulçumanos','Budistas','Taoístas','Ateus','Cristãos protestantes',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Entre os historiadores, existe o consenso de que o saber histórico é construído a partir de fontes. Portanto, é incorreto afirmar que as fontes históricas são:','somente documentos escritos, aos quais é possível aplicar a crítica pelos métodos científicos do saber histórico','diversos tipos de referência do passado, dentre os quais se incluem escritos, manuscritos, imagens, patrimônio arquitetônico e cultural – de tipo material ou simbólicos','utensílios, ferramentas e artefatos produzidos pelos homens, que chegaram até o presente, servindo de testemunho de práticas humanas já vividas','signos, sinais e vestígios do passado dos homens que são recolhidos','todas as referências de atividades humanas, pois compõem o patrimônio cultural de todo e qualquer grupo humano, servindo de indicadores do seu passado',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Que países já passaram por um regime totalitarista no século XX?','Alemanha e Itália','Espanha e Brasil','Inglaterra e Itália','Rússia e EUA','Brasil e Alemanha',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Sobre o sistema feudal europeu, é incorreto afirmar que:','a economia era baseada no comércio, devido à alta produção de excedentes agrícolas','o feudo constituía sua unidade básica de produção','neste regime, os servos eram obrigados a prestar serviços gratuitos e ceder a maior parte da produção ao senhor feudal e, em troca, recebiam do senhor feudal proteção militar','as duas principais camadas sociais eram a dos senhores feudais e a dos servos da gleba','cada feudo representava uma unidade politicamente autônoma',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('A Primeira Revolução Industrial, iniciada em fins do século XVIII, provocou várias transformações na sociedade européia, tais como:','transferência do centro econômico das áreas rurais para as urbanas —afirmação do poder econômico da burguesia — consolidação do capitalismo como sistema dominante','intensificação das intervenções estatais na economia — surgimento do operariado — fortalecimento do controle político das metrópoles sobre suas colônias','difusão dos princípios comunistas — produção em grande escala direcionada para o mercado internacional — melhoria das condições de vida e trabalho no meio urbano','crise do regime capitalista — consolidação da propriedade privada dos meios de produção — redução dos conflitos armados entre as nações européias','aumento quantidade de produtos industrializados — terceirização do setor público — fortalecimento político associado à ascenção do operariado',0,0,0,0,0,0,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Acerca da década de 1980 no Brasil podemos afirmar, do ponto de vista econômico, que foi um período:','de recessão das atividades econômicas, tanto que muitos o consideram uma década perdida','de grande expansão, embora fortemente perturbado pelas incertezas quanto à consolidação da democracia','de forte desenvolvimento da indústria, ainda que não acompanhado por outros setores da economia','de recomposição da mão de obra, como resultado do declínio das migrações','de ampla abertura ao capital estrangeiro, propiciando por essa via o aumento do produto interno bruto',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Na Alemanha, o livro "Mein Kampf" (Minha Luta) está banido até o ano de 2015. Em que época Adolf Hitler escreveu este livro?','Nos anos 20, a partir da experiência na prisão, na Baviera, por liderar um golpe fracassado','Durante a sua experiência como soldado, na Primeira Guerra','Em 1939, após a invasão da Polônia e a defesa pública do extermínio dos judeus','Nas semanas finais da Segunda Guerra, refugiado no bunker, em Berlim','Durante a República de Weimar, no qual Hitler era chanceler',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Na mitologia grega','quem derrotou a Hidra?, Hércules','Aquiles','Teseu','Perseu','Prometeu',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual é o nome dado a reforma agrária que levou o Brasil à uma grande inflação em 1891?','Encilhamento','Economia Neoliberal','Economia Federalista','Economia da Regência governamental','Economia Provisória',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual era o nome do sistema religioso que estava em rigor entre o Estado e a igreja durante a república brasileira?','Padroado','Padroeira','Catolicismo','Mantiqueira','Religião do livre passo',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Entre as causas do declínio das cidades-estado (pólis) da Grécia, é possível destacar o(a):','rivalidade entre as cidades e a disputa pela hegemonia grega','invasão e dominação persa','expansão cartaginesa pelo Mediterrâneo','expansão do Império Romano','desaparecimento e morte dos principais reis gregos, quando retornavam da Guerra de Tróia',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('O século XIV, na Idade Média, corresponde a uma fase em que o feudalismo já estava enfrentando sérios problemas, que impunham mudanças. Não fez parte dessa fase de crise do feudalismo o(a):','política oficial explicita de contenção da produção agrícola e do crescimento demográfico','escassez da mão-de-obra servil, devido a epidemias como a “Peste Negra”, doença que dizimou grande parcela da população','desorganização da produção causada pela incidência de guerras, como a Guerra dos Cem Anos','aumento da mortalidade provocada pela Grande Fome, que produziu a miséria no campo','eclosão de revoltas camponesas desencadeadas pela situação de empobrecimento do homem do campo',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('O crescimento do comércio e das cidades na Baixa Idade Média:','fez surgir um novo grupo social, ligado às atividades artesanais e mercantis','consolidou as estruturas feudais, como a economia de subsistência e a suserania','expandiu as atividades agrícolas, com o declínio do uso de moedas nas trocas','permitiu o desenvolvimento do trabalho livre, isento de quaisquer restrições','criou uma infra-estrutura tão adequada, que provocou intenso êxodo rural',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Assinale a alternativa que não se relaciona com o movimento de expansão marítima portuguesa','A unificação Italiana foi um dos pré-requisitos para a expansão marítima','No início da Idade Moderna, o oceano Atlântico era praticamente desconhecido, havendo navegações costeiras de Portugal aos países escandinavos: Dinamarca, Noruega e Suécia','Investimentos altos foram necessários à expansão portuguesa. O Estado foi o único agente capaz de investir grandes vultos, advindos de impostos recolhidos sobre a propriedade da terra','A conquista de Ceuta em 1415 significou uma aliança de interesses entre a burguesia e a nobreza portuguesa cujos objetivos eram convergentes, na época','Os lucros comerciais atingidos com as expedições portuguesas de 1415 e 1460 na costa africana, foram superiores aos gastos realizados nesses empreendimentos',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Quando os espanhóis conquistaram as terras do continente americano recorreram ao trabalho indígena para desenvolver a produção econômica, adotando, como formas de exploração do trabalho dos indígenas:','a mita e a encomienda','a hacienda e a plantagem','a mita e o arrendamento','a corvéia e o asiento','a parceria e a encomienda',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Sobre a constituição de 1891 no Brasil, podemos afirmar que foi','presidencialista e laica','parlamentarista e liberal','centralizadora e liberal','positivista e laica','presidencialista e positivista',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Que presidente renunciou ao cargo 7 meses depois de assumir dizendo: Fui vencido pela reação e assim deixo o governo. Nestes sete meses cumpri o meu dever...?','Jânio Quadros','Rodrigues Alves','Getúlio Vargas','Fernando Collor de Melo','Café Filho',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Na Mitologia Grega, quem matou e arrancou a cabeça da Medusa?','Perseu','Aquiles','Pégaso','Jasão',' Zeus',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('A peste, a fome e a guerra constituíram os elementos mais visíveis e terríveis do que se conhece como a crise do século XIV. Como conseqüência dessa crise, ocorrida na Baixa Idade Média','o processo de centralização e concentração do poder político intensificou-se até se tornar absoluto, no início da modernidade','o movimento de reforma do cristianismo foi interrompido por mais de um século, antes de reaparecer com Lutero e iniciar a modernidade','o campesinato, que estava em vias de conquistar a liberdade, voltou novamente a cair, por mais de um século, na servidão feudal','o feudalismo entrou em colapso no campo, mas manteve sua dominação sobre a economia urbana até o fim do Antigo Regime','entre as classes sociais, a nobreza foi a menos prejudicada pela crise, ao contrário do que ocorreu com a burguesia',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Sobre o governo de Juan Domingo Perón ( 1946 - 1955 ) na Argentina, podemos afirmar que','foi um governo com uma retórica nacionalista, que recebeu dos descamisados importante sustentação política','recebeu expressivo apoio de parte importante da classe trabalhadora, ainda que não lhe tenha concedido benefícios concretos','deslocou o centro das atenções políticas para a figura carismática de Eva Perón, discreta e secundária','foi um governo ditatorial, pois fechou o Congresso e colocou os partidos políticos na ilegalidade','buscou persistentemente, no plano internacional, uma aliança com os Estados Unidos',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('O sistema econômico, social e político do Império Romano funcionou bem nos três primeiros séculos da Era Cristã; a partir de então, começou uma crise que o levou à desintegração no século V. Qual dos itens a seguir indica uma das causas reais da queda do Império Romano?','A redução na produção dos latifúndios, em razão da falta de escravos.','O assassinato de Júlio César.','O governo de Sila, que entre outras medidas, elevou para 600 o número de senadores romanos.','A reforma agrária instituída por Tibério Graco.','O abalo causado ao Império pelas Guerras Púnicas.',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Os estudos recentes sobre a Idade Média avaliam esse período da história como um(a):','época que não se constitui uma unidade: em sua primeira fase, houve retrocesso cultural e econômico, porém, posteriormente, ressurgiu a vida econômica e houve grande florescimento cultural.','período de dez séculos durante o qual houve intensa atividade industrial e comercial, sendo a cultura intelectual exclusividade dos mosteiros e da Igreja;','período de obscurantismo e atraso cultural – a longa noite de mil anos – em virtude do desprezo dado à herança intelectual grega e romana da época precedente;','época que pode ser chamada de “Idade das Trevas”, em razão do predomínio da Igreja, que, com sua ideologia, contribuiu para a estagnação cultural, a opressão política e o fanatismo religioso;','período de estagnação completa tanto no setor econômico e político, quanto na cultura intelectual.',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Cinquecento foi o período de plena maturidade do Renascimento na Europa. São autores expressivos dessa fase na literatura (política ou não), na pintura e na ciência, respectivamente:','Maquiavel (1469-1527), Leonardo da Vinci (1452-1519) e Nicolau Copérnico (1473-1543).','Dante Alighieri (1265-1321), Maquiavel (1469-1527), e Sandro Botticelli (1444/5-1510).','Dante Alighieri (1265-1321), Giotti de Bondone (1266-1327) e Nicolau Copérnico (1473-1543).','Maquiavel (1469-1527), Nicolau Copérnico (1473-1543) e Francis Bacon (1561-1657).','Maquiavel (1469-1527), Dante Alighieri (1265-1321) e Giotti de Bondone (1266-1327).',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Durante o período de 1889 a 1930 conhecido como República Velha, persiste como herança da fase monárquica','a produção agrícola centrada na agricultura cafeeira e na grande unidade agroprodutora.','o unitarismo político e o sistema de voto censitário, exclusivo da população de renda elevada.','a supremacia da região nordestina em termos econômicos e concentração demográfica.','uma economia de impulso industrializante inaugurada com a “Era Mauá”, no século XIX.','a hegemonia do Exército como principal sustentáculo do poder político e da representação das classes urbanas.',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('O governo de Fernando Henrique Cardoso segue linhas acordadas pelo Consenso de Washington, realizado em 1989. Tal consenso, de caráter neoliberal, adotou um conjunto de medidas para controlar a inflação e modernizar o Estado. Entre estas medidas estão:','privatização, abertura financeira e investimentos em infra-estrutura básica.','ajuste fiscal, redução do tamanho do Estado e fortalecimento das empresas estatais.','fortalecimento do sistema previdenciário atual, privatização e investimentos em infraestrutura básica.','ajuste fiscal, restrições econômicas às importações de gêneros agrícolas e abertura financeira.','abertura comercial, abertura financeira e regulamentação do funcionamento da economia.',0,0,0,0,0,1,2)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('No filme Avatar, qual a cor da pele dos Na’Vi?','Azul','Laranja','Vermelha','Amarela','Verde',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual ator é o protagonista da série de filmes Indiana Jones?','Harrison Ford','Sean Connery','River Phoenix','Richard Gere','Thomas Toorbando',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('No filme Indiana Jones e o Reino da Caveira de Cristal, qual atriz interpreta a agente Irina Spalko?','Cate Blanchett','Shia LaBeouf','Tori Lane','Diane Tasnarrada','Kirina Jepecozoul',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('No filme Homem Aranha o personagem Peter Parker é picado por um(a):','Aranha','Abelha','Jumento','Cisne','Escorpião',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('O personagem Wolverine é um herói da história:','X-Men','Super-homem','Homem-aranha','Nogueira e sua gangue','Turma da Mônica',0,0,0,0,0,0,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Qual ator/atriz não participa no primeiro filme Homem de Ferro?','Scarlett Johansson','Robert Downey Jr.','Terrence Howard','Gwyneth Paltrow','Jeff Bridges',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Os atores Johnny Depp, Bill Murray, Bruce Willis, Michael Douglas e Mark Wahlberg foram cotados para atuar em um filme mas nem todos ou nenhum acabou participando do mesmo. Que filme é esse?','Onze homens e um segredo','Senhor dos Anéis','Scooby Doo','Armageddon','Chicago',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('O filme Casablanca tem como plano de fundo:','A fuga da Europa ocupada pelos nazistas na Segunda Guerra Mundial','A história da máfia italiana nos Estados Unidos','A situação sócio-econômica da Inglaterra após a Primeira Guerra Mundial','Um intenso romance vivido por dois jovens ingleses','A história de vida de John Largedick Nogueira, um importante político americano',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('No filme O Poderoso Chefão, qual atriz interpreta a namorada de Michael, Kay Adams?','Diane Keaton','Morgana King','Jeannie Linero','Simonetta Stefanelli','Sandra Willows',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('No filme Advogado do Diabo o ator Al Pacino interpreta o personagem:','John Milton','Eddie Barzoon','Adam Eve','Craig Deville','Kevin Lomax',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('No filme Clube da Luta, qual ator interpreta o personagem Jack?','Edward Norton','Antonio Banderas','Brad Pitt','Morgan Freeman','Bruce Willis',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('No filme Missão Impossível, o grupo especial de agentes liderado por Ethan Hunt (Tom Cruise) é emboscado em qual cidade européia?','Praga','Budapeste','Dublin','Bucareste','Viena',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Sean Connery participou de diversos títulos de 007, como Goldfinger e Thunderball. Entretanto, entre dois filmes protagonizados por Sean Connery houve um filme em 1969 no qual outro ator foi o 007. Qual é esse ator?','George Lazenby','Roger Moore','Timothy Dalton','Pierce Brosnan','Telly Savalas',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('No filme Tropa de Elite, qual o ano corrente da história?','1997','1995','1996','1998','1999',0,0,0,0,0,1,1)
INSERT INTO dbo.Perguntas (enunciado, alternativaCorreta, alternativaIncorreta1, alternativaIncorreta2, alternativaIncorreta3, alternativaIncorreta4, vezesRespondidaAltCorreta, vezesRespondidaAltIncorreta1, vezesRespondidaAltIncorreta2, vezesRespondidaAltIncorreta3, vezesRespondidaAltIncorreta4, dificuldade, Tema_IdTema)
        VALUES ('Em qual destes filmes o ator Anthony Hopkins não teve participação?','Adorável Vagabundo','Missão Impossível 2','Hannibal','Dragão Vermelho','A Máscara do Zorro',0,0,0,0,0,1,1)
GO
