//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ShowPerguntas", "FK_PerguntaTema", "Temas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ShowPerguntas.Dados.Tema), "Perguntas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ShowPerguntas.Dados.Pergunta), true)]
[assembly: EdmRelationshipAttribute("ShowPerguntas", "FK_RankingUsuario", "Usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ShowPerguntas.Dados.Usuario), "Rankings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ShowPerguntas.Dados.Ranking), true)]

#endregion

namespace ShowPerguntas.Dados
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Show_de_PerguntasEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Show_de_PerguntasEntities object using the connection string found in the 'Show_de_PerguntasEntities' section of the application configuration file.
        /// </summary>
        public Show_de_PerguntasEntities() : base("name=Show_de_PerguntasEntities", "Show_de_PerguntasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Show_de_PerguntasEntities object.
        /// </summary>
        public Show_de_PerguntasEntities(string connectionString) : base(connectionString, "Show_de_PerguntasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Show_de_PerguntasEntities object.
        /// </summary>
        public Show_de_PerguntasEntities(EntityConnection connection) : base(connection, "Show_de_PerguntasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pergunta> Perguntas
        {
            get
            {
                if ((_Perguntas == null))
                {
                    _Perguntas = base.CreateObjectSet<Pergunta>("Perguntas");
                }
                return _Perguntas;
            }
        }
        private ObjectSet<Pergunta> _Perguntas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ranking> Rankings
        {
            get
            {
                if ((_Rankings == null))
                {
                    _Rankings = base.CreateObjectSet<Ranking>("Rankings");
                }
                return _Rankings;
            }
        }
        private ObjectSet<Ranking> _Rankings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tema> Temas
        {
            get
            {
                if ((_Temas == null))
                {
                    _Temas = base.CreateObjectSet<Tema>("Temas");
                }
                return _Temas;
            }
        }
        private ObjectSet<Tema> _Temas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Perguntas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPerguntas(Pergunta pergunta)
        {
            base.AddObject("Perguntas", pergunta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rankings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRankings(Ranking ranking)
        {
            base.AddObject("Rankings", ranking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Temas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTemas(Tema tema)
        {
            base.AddObject("Temas", tema);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShowPerguntas", Name="Pergunta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pergunta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pergunta object.
        /// </summary>
        /// <param name="idPergunta">Initial value of the IdPergunta property.</param>
        /// <param name="enunciado">Initial value of the enunciado property.</param>
        /// <param name="dificuldade">Initial value of the dificuldade property.</param>
        /// <param name="alternativaCorreta">Initial value of the alternativaCorreta property.</param>
        /// <param name="alternativaIncorreta1">Initial value of the alternativaIncorreta1 property.</param>
        /// <param name="alternativaIncorreta2">Initial value of the alternativaIncorreta2 property.</param>
        /// <param name="alternativaIncorreta3">Initial value of the alternativaIncorreta3 property.</param>
        /// <param name="alternativaIncorreta4">Initial value of the alternativaIncorreta4 property.</param>
        /// <param name="tema_IdTema">Initial value of the Tema_IdTema property.</param>
        public static Pergunta CreatePergunta(global::System.Int32 idPergunta, global::System.String enunciado, global::System.Int32 dificuldade, global::System.String alternativaCorreta, global::System.String alternativaIncorreta1, global::System.String alternativaIncorreta2, global::System.String alternativaIncorreta3, global::System.String alternativaIncorreta4, global::System.Int32 tema_IdTema)
        {
            Pergunta pergunta = new Pergunta();
            pergunta.IdPergunta = idPergunta;
            pergunta.enunciado = enunciado;
            pergunta.dificuldade = dificuldade;
            pergunta.alternativaCorreta = alternativaCorreta;
            pergunta.alternativaIncorreta1 = alternativaIncorreta1;
            pergunta.alternativaIncorreta2 = alternativaIncorreta2;
            pergunta.alternativaIncorreta3 = alternativaIncorreta3;
            pergunta.alternativaIncorreta4 = alternativaIncorreta4;
            pergunta.Tema_IdTema = tema_IdTema;
            return pergunta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPergunta
        {
            get
            {
                return _IdPergunta;
            }
            set
            {
                if (_IdPergunta != value)
                {
                    OnIdPerguntaChanging(value);
                    ReportPropertyChanging("IdPergunta");
                    _IdPergunta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPergunta");
                    OnIdPerguntaChanged();
                }
            }
        }
        private global::System.Int32 _IdPergunta;
        partial void OnIdPerguntaChanging(global::System.Int32 value);
        partial void OnIdPerguntaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String enunciado
        {
            get
            {
                return _enunciado;
            }
            set
            {
                OnenunciadoChanging(value);
                ReportPropertyChanging("enunciado");
                _enunciado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("enunciado");
                OnenunciadoChanged();
            }
        }
        private global::System.String _enunciado;
        partial void OnenunciadoChanging(global::System.String value);
        partial void OnenunciadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dificuldade
        {
            get
            {
                return _dificuldade;
            }
            set
            {
                OndificuldadeChanging(value);
                ReportPropertyChanging("dificuldade");
                _dificuldade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dificuldade");
                OndificuldadeChanged();
            }
        }
        private global::System.Int32 _dificuldade;
        partial void OndificuldadeChanging(global::System.Int32 value);
        partial void OndificuldadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alternativaCorreta
        {
            get
            {
                return _alternativaCorreta;
            }
            set
            {
                OnalternativaCorretaChanging(value);
                ReportPropertyChanging("alternativaCorreta");
                _alternativaCorreta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alternativaCorreta");
                OnalternativaCorretaChanged();
            }
        }
        private global::System.String _alternativaCorreta;
        partial void OnalternativaCorretaChanging(global::System.String value);
        partial void OnalternativaCorretaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alternativaIncorreta1
        {
            get
            {
                return _alternativaIncorreta1;
            }
            set
            {
                OnalternativaIncorreta1Changing(value);
                ReportPropertyChanging("alternativaIncorreta1");
                _alternativaIncorreta1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alternativaIncorreta1");
                OnalternativaIncorreta1Changed();
            }
        }
        private global::System.String _alternativaIncorreta1;
        partial void OnalternativaIncorreta1Changing(global::System.String value);
        partial void OnalternativaIncorreta1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alternativaIncorreta2
        {
            get
            {
                return _alternativaIncorreta2;
            }
            set
            {
                OnalternativaIncorreta2Changing(value);
                ReportPropertyChanging("alternativaIncorreta2");
                _alternativaIncorreta2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alternativaIncorreta2");
                OnalternativaIncorreta2Changed();
            }
        }
        private global::System.String _alternativaIncorreta2;
        partial void OnalternativaIncorreta2Changing(global::System.String value);
        partial void OnalternativaIncorreta2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alternativaIncorreta3
        {
            get
            {
                return _alternativaIncorreta3;
            }
            set
            {
                OnalternativaIncorreta3Changing(value);
                ReportPropertyChanging("alternativaIncorreta3");
                _alternativaIncorreta3 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alternativaIncorreta3");
                OnalternativaIncorreta3Changed();
            }
        }
        private global::System.String _alternativaIncorreta3;
        partial void OnalternativaIncorreta3Changing(global::System.String value);
        partial void OnalternativaIncorreta3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String alternativaIncorreta4
        {
            get
            {
                return _alternativaIncorreta4;
            }
            set
            {
                OnalternativaIncorreta4Changing(value);
                ReportPropertyChanging("alternativaIncorreta4");
                _alternativaIncorreta4 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("alternativaIncorreta4");
                OnalternativaIncorreta4Changed();
            }
        }
        private global::System.String _alternativaIncorreta4;
        partial void OnalternativaIncorreta4Changing(global::System.String value);
        partial void OnalternativaIncorreta4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vezesRespondidaAltCorreta
        {
            get
            {
                return _vezesRespondidaAltCorreta;
            }
            set
            {
                OnvezesRespondidaAltCorretaChanging(value);
                ReportPropertyChanging("vezesRespondidaAltCorreta");
                _vezesRespondidaAltCorreta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vezesRespondidaAltCorreta");
                OnvezesRespondidaAltCorretaChanged();
            }
        }
        private global::System.Int32 _vezesRespondidaAltCorreta = 0;
        partial void OnvezesRespondidaAltCorretaChanging(global::System.Int32 value);
        partial void OnvezesRespondidaAltCorretaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vezesRespondidaAltIncorreta1
        {
            get
            {
                return _vezesRespondidaAltIncorreta1;
            }
            set
            {
                OnvezesRespondidaAltIncorreta1Changing(value);
                ReportPropertyChanging("vezesRespondidaAltIncorreta1");
                _vezesRespondidaAltIncorreta1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vezesRespondidaAltIncorreta1");
                OnvezesRespondidaAltIncorreta1Changed();
            }
        }
        private global::System.Int32 _vezesRespondidaAltIncorreta1 = 0;
        partial void OnvezesRespondidaAltIncorreta1Changing(global::System.Int32 value);
        partial void OnvezesRespondidaAltIncorreta1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vezesRespondidaAltIncorreta2
        {
            get
            {
                return _vezesRespondidaAltIncorreta2;
            }
            set
            {
                OnvezesRespondidaAltIncorreta2Changing(value);
                ReportPropertyChanging("vezesRespondidaAltIncorreta2");
                _vezesRespondidaAltIncorreta2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vezesRespondidaAltIncorreta2");
                OnvezesRespondidaAltIncorreta2Changed();
            }
        }
        private global::System.Int32 _vezesRespondidaAltIncorreta2 = 0;
        partial void OnvezesRespondidaAltIncorreta2Changing(global::System.Int32 value);
        partial void OnvezesRespondidaAltIncorreta2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vezesRespondidaAltIncorreta3
        {
            get
            {
                return _vezesRespondidaAltIncorreta3;
            }
            set
            {
                OnvezesRespondidaAltIncorreta3Changing(value);
                ReportPropertyChanging("vezesRespondidaAltIncorreta3");
                _vezesRespondidaAltIncorreta3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vezesRespondidaAltIncorreta3");
                OnvezesRespondidaAltIncorreta3Changed();
            }
        }
        private global::System.Int32 _vezesRespondidaAltIncorreta3 = 0;
        partial void OnvezesRespondidaAltIncorreta3Changing(global::System.Int32 value);
        partial void OnvezesRespondidaAltIncorreta3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vezesRespondidaAltIncorreta4
        {
            get
            {
                return _vezesRespondidaAltIncorreta4;
            }
            set
            {
                OnvezesRespondidaAltIncorreta4Changing(value);
                ReportPropertyChanging("vezesRespondidaAltIncorreta4");
                _vezesRespondidaAltIncorreta4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vezesRespondidaAltIncorreta4");
                OnvezesRespondidaAltIncorreta4Changed();
            }
        }
        private global::System.Int32 _vezesRespondidaAltIncorreta4 = 0;
        partial void OnvezesRespondidaAltIncorreta4Changing(global::System.Int32 value);
        partial void OnvezesRespondidaAltIncorreta4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tema_IdTema
        {
            get
            {
                return _Tema_IdTema;
            }
            set
            {
                OnTema_IdTemaChanging(value);
                ReportPropertyChanging("Tema_IdTema");
                _Tema_IdTema = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tema_IdTema");
                OnTema_IdTemaChanged();
            }
        }
        private global::System.Int32 _Tema_IdTema;
        partial void OnTema_IdTemaChanging(global::System.Int32 value);
        partial void OnTema_IdTemaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShowPerguntas", "FK_PerguntaTema", "Temas")]
        public Tema Tema
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tema>("ShowPerguntas.FK_PerguntaTema", "Temas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tema>("ShowPerguntas.FK_PerguntaTema", "Temas").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tema> TemaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tema>("ShowPerguntas.FK_PerguntaTema", "Temas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tema>("ShowPerguntas.FK_PerguntaTema", "Temas", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShowPerguntas", Name="Ranking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ranking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ranking object.
        /// </summary>
        /// <param name="idRanking">Initial value of the IdRanking property.</param>
        /// <param name="pontuacaoMaxima">Initial value of the pontuacaoMaxima property.</param>
        public static Ranking CreateRanking(global::System.Int32 idRanking, global::System.Int32 pontuacaoMaxima)
        {
            Ranking ranking = new Ranking();
            ranking.IdRanking = idRanking;
            ranking.pontuacaoMaxima = pontuacaoMaxima;
            return ranking;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdRanking
        {
            get
            {
                return _IdRanking;
            }
            set
            {
                if (_IdRanking != value)
                {
                    OnIdRankingChanging(value);
                    ReportPropertyChanging("IdRanking");
                    _IdRanking = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdRanking");
                    OnIdRankingChanged();
                }
            }
        }
        private global::System.Int32 _IdRanking;
        partial void OnIdRankingChanging(global::System.Int32 value);
        partial void OnIdRankingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pontuacaoMaxima
        {
            get
            {
                return _pontuacaoMaxima;
            }
            set
            {
                OnpontuacaoMaximaChanging(value);
                ReportPropertyChanging("pontuacaoMaxima");
                _pontuacaoMaxima = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pontuacaoMaxima");
                OnpontuacaoMaximaChanged();
            }
        }
        private global::System.Int32 _pontuacaoMaxima;
        partial void OnpontuacaoMaximaChanging(global::System.Int32 value);
        partial void OnpontuacaoMaximaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UsuarioIdUsuario
        {
            get
            {
                return _UsuarioIdUsuario;
            }
            set
            {
                OnUsuarioIdUsuarioChanging(value);
                ReportPropertyChanging("UsuarioIdUsuario");
                _UsuarioIdUsuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UsuarioIdUsuario");
                OnUsuarioIdUsuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _UsuarioIdUsuario;
        partial void OnUsuarioIdUsuarioChanging(Nullable<global::System.Int32> value);
        partial void OnUsuarioIdUsuarioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShowPerguntas", "FK_RankingUsuario", "Usuarios")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("ShowPerguntas.FK_RankingUsuario", "Usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("ShowPerguntas.FK_RankingUsuario", "Usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("ShowPerguntas.FK_RankingUsuario", "Usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("ShowPerguntas.FK_RankingUsuario", "Usuarios", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShowPerguntas", Name="Tema")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tema : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tema object.
        /// </summary>
        /// <param name="idTema">Initial value of the IdTema property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        public static Tema CreateTema(global::System.Int32 idTema, global::System.String descricao)
        {
            Tema tema = new Tema();
            tema.IdTema = idTema;
            tema.descricao = descricao;
            return tema;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTema
        {
            get
            {
                return _IdTema;
            }
            set
            {
                if (_IdTema != value)
                {
                    OnIdTemaChanging(value);
                    ReportPropertyChanging("IdTema");
                    _IdTema = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTema");
                    OnIdTemaChanged();
                }
            }
        }
        private global::System.Int32 _IdTema;
        partial void OnIdTemaChanging(global::System.Int32 value);
        partial void OnIdTemaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShowPerguntas", "FK_PerguntaTema", "Perguntas")]
        public EntityCollection<Pergunta> Perguntas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pergunta>("ShowPerguntas.FK_PerguntaTema", "Perguntas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pergunta>("ShowPerguntas.FK_PerguntaTema", "Perguntas", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShowPerguntas", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="sobrenome">Initial value of the sobrenome property.</param>
        /// <param name="login">Initial value of the login property.</param>
        /// <param name="senha">Initial value of the senha property.</param>
        /// <param name="dataCadastro">Initial value of the dataCadastro property.</param>
        public static Usuario CreateUsuario(global::System.Int32 idUsuario, global::System.String nome, global::System.String sobrenome, global::System.String login, global::System.String senha, global::System.DateTime dataCadastro)
        {
            Usuario usuario = new Usuario();
            usuario.IdUsuario = idUsuario;
            usuario.nome = nome;
            usuario.sobrenome = sobrenome;
            usuario.login = login;
            usuario.senha = senha;
            usuario.dataCadastro = dataCadastro;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sobrenome
        {
            get
            {
                return _sobrenome;
            }
            set
            {
                OnsobrenomeChanging(value);
                ReportPropertyChanging("sobrenome");
                _sobrenome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sobrenome");
                OnsobrenomeChanged();
            }
        }
        private global::System.String _sobrenome;
        partial void OnsobrenomeChanging(global::System.String value);
        partial void OnsobrenomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dataCadastro
        {
            get
            {
                return _dataCadastro;
            }
            set
            {
                OndataCadastroChanging(value);
                ReportPropertyChanging("dataCadastro");
                _dataCadastro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dataCadastro");
                OndataCadastroChanged();
            }
        }
        private global::System.DateTime _dataCadastro;
        partial void OndataCadastroChanging(global::System.DateTime value);
        partial void OndataCadastroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShowPerguntas", "FK_RankingUsuario", "Rankings")]
        public EntityCollection<Ranking> Rankings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ranking>("ShowPerguntas.FK_RankingUsuario", "Rankings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ranking>("ShowPerguntas.FK_RankingUsuario", "Rankings", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
